module.exports = {
  DIRECTOR: 'DIRECTOR',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
  WAREHOUSE_EMPLOYEE: 'WAREHOUSE_EMPLOYEE',
  TRANSACTION_MANAGER: 'TRANSACTION_MANAGER',
  TRANSACTION_EMPLOYEE: 'TRANSACTION_EMPLOYEE',
  DELIVER: 'DELIVER',
  GUEST: 'GUEST'
}